# Generated by Django 3.2.9 on 2022-02-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_auto_20220213_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('update',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='regist',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top.course'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient1', to='top.ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient2', to='top.ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient3', to='top.ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient4', to='top.ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient5', to='top.ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='regist',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top.type'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='regist',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='regist',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
