# Generated by Django 3.2.9 on 2022-02-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0003_auto_20220213_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='del_flg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='del_flg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='del_flg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='del_flg',
            field=models.IntegerField(default=0),
        ),
    ]
